# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Install dependencies on server (Diaz)

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Starting manual override for installing node dependencies (Y/n):'
        # Default value if no value is explicitly provided
        default: 'Y'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - run: echo "Installing node dependencies..."
      - run: cd /apps/lrbc
      - run: sudo npm install
      - run: echo "Done."
